#!/usr/bin/env bash
#writing a script that transfers a file from my machine to the server

#checking to ensure that 4 parameters are passed
if [ $# -ne 4 ]; then
    echo  "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY "
    exit 1
fi
file="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

#ensuring the file is securely copied using scp
#disabling host key checking usinf the -o flag
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file" "$username@$server_ip":~/