#!/usr/bin/env bash
#installing nginx 

sudo apt update -y -qq
sudo apt install nginx -y

#bypassing the firewall
sudo ufw allow 'NGINX HTTP'

#starting nginx
sudo service nginx start

#giving the owner ownership to website files for easy editing
sudo chown -R "$USER": "$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# Setting up /redirect_me to a youtube video
sudo sed -i '24i\       
        rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

#reload nginx
sudo service nginx reload
